[package]
name = "uhid-virt-ng"
version = "0.0.1"
authors = ["Marco Scardovi <scardracs@disroot.org>"]
edition = "2024"
rust-version = "1.93"
description = "Interface to Linux UHID (user-space HID transport drivers)"
repository = "https://github.com/scardracs/uhid-virt-ng"
license = "MIT"
readme = "README.md"
keywords = ["hid", "uhid", "linux", "userspace", "transport"]
categories = ["os", "os::unix-apis"]
exclude = [
    "example/"
]

[lib]
doc = true
test = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "deny"
non_ascii_idents = "deny"
unused_qualifications = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
undocumented_unsafe_blocks = "deny"
multiple_unsafe_ops_per_block = "deny"
missing_safety_doc = "deny"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
dbg_macro = "deny"
print_stdout = "deny"
print_stderr = "deny"
doc_markdown = "deny"
missing_panics_doc = "deny"
must_use_candidate = "deny"
semicolon_if_nothing_returned = "deny"
